# Generated by Django 3.2.2 on 2021-05-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formtaken', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='oxyzendetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliername', models.CharField(max_length=50)),
                ('contactnumber', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('about', models.CharField(max_length=500)),
            ],
        ),
    ]
