# Generated by Django 3.2.2 on 2021-05-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formtaken', '0002_oxyzendetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='carditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardtitle', models.CharField(max_length=100)),
                ('cardtext', models.CharField(max_length=1000)),
                ('cardfooter', models.CharField(max_length=100)),
            ],
        ),
    ]
